### ISSUE TITLE
[Feature Request] 像 Leetcode 一样增加每月打卡勋章

### ISSUE THREAD

**Issue by tsreaper** [Yawn-Sean/Daily_CF_Problems#53]
像 Leetcode 一样增加每月打卡勋章 🎖

**Comment by Yawn-Sean** [comment]
可能没有设计勋章的方法，但是可以加个君子协定打卡，在一个 .md 下大伙可以自己记录自己打卡情况，然后一个月都打卡，可能在昵称旁边加个可累计的符号（完全没想好呢！
